version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: autherdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    command: >
      bash -c "
        alembic upgrade head &&
        uvicorn src.main:app --host 0.0.0.0 --port 8000
      "
    volumes:
      - .:/code
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: autherdb
      PASS_SALT: some_random_secret_salt_123
      SECRET_KEY: very_very_secret_jwt_key_098760
      ALGORITHM: HS256
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: IvanMelnikovF@gmail.com 
      SMTP_PASS: mzog gdoq hxsa bjmi
      EXP_ACCESS: 1h
      EXP_EMAIL: 1h
      EXP_REFRESH: 24h
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  db_data:
  